name: e2e automation tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update Chrome to latest version
      run:  |
        sudo apt-get update
        sudo apt-get --only-upgrade install google-chrome-stable
        google-chrome --version

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Run e2e automation tests
      working-directory: e2e
      run: ./gradlew build

    - name: Upload Selenium screenshots
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: screenshots
        path: /home/runner/work/portfolio-react/portfolio-react/e2e/app/screenshots/